# Generated by Django 3.0.8 on 2020-07-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200716_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_desc',
        ),
    ]
